import type { Metadata } from "next";
import { AppsInfoSheetProvider } from "../providers/apps-info-sheet";

import { AppsSidebar } from "./components/apps-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppsInfoSheetProvider>
      <div className="flex">
        <AppsSidebar className="hidden xl:block" />
        <div className="flex-1 min-w-0">{children}</div>
      </div>
    </AppsInfoSheetProvider>
  );
}
