export const AppConfig = {
  title: "Sample-Site",
  description: "Generated by create next app",
  company: "Sample-Company Inc.",
  address: "1234-5678-9012",
  representative: "Sample-Representative",
  department: "Sample-Department",
  email: "sample@example.com",
};
