import { z } from "zod";

export const createPolicySchema = z.object({
  // displayName: z.string().trim().min(1),
  screenCaptureDisabled: z.boolean().default(false),
  cameraDisabled: z.boolean().default(false),
  // keyguardDisabledFeatures: z.enum(["none", "secure", "trust", "disabled"]),
  // defaultPermissionPolicy: z.enum(["prompt", "grant", "deny"]),
  // accountTypesWithManagementDisabled: z.string(),
  addUserDisabled: z.boolean().default(false),
  adjustVolumeDisabled: z.boolean().default(false),
  factoryResetDisabled: z.boolean().default(false),
  installAppsDisabled: z.boolean().default(false),
  mountPhysicalMediaDisabled: z.boolean().default(false),
  modifyAccountsDisabled: z.boolean().default(false),
  safeBootDisabled: z.boolean().default(false),
  uninstallAppsDisabled: z.boolean().default(false),
  keyguardDisabled: z.boolean().default(false),
  minimumApiLevel: z.number().int().positive(),
  bluetoothContactSharingDisabled: z.boolean().default(false),
  // shortSupportMessage: z.string(),
  // longSupportMessage: z.string(),
  bluetoothConfigDisabled: z.boolean().default(false),
  cellBroadcastsConfigDisabled: z.boolean().default(false),
  credentialsConfigDisabled: z.boolean().default(false),
  mobileNetworksConfigDisabled: z.boolean().default(false),
  vpnConfigDisabled: z.boolean().default(false),
  wifiConfigDisabled: z.boolean().default(false),
  createWindowsDisabled: z.boolean().default(false),
  networkResetDisabled: z.boolean().default(false),
  outgoingBeamDisabled: z.boolean().default(false),
  outgoingCallsDisabled: z.boolean().default(false),
  removeUserDisabled: z.boolean().default(false),
  shareLocationDisabled: z.boolean().default(false),
  smsDisabled: z.boolean().default(false),
  unmuteMicrophoneDisabled: z.boolean().default(false),
  usbFileTransferDisabled: z.boolean().default(false),
  ensureVerifyAppsEnabled: z.boolean().default(false),
  // appAutoUpdatePolicy: z.enum([
  //   "choiceToUser",
  //   "neverUpdate",
  //   "wifiOnly",
  //   "alwaysUpdate",
  // ]),
  kioskCustomLauncherEnabled: z.boolean().default(false),
  skipFirstUseHintsEnabled: z.boolean().default(false),
  privateKeySelectionEnabled: z.boolean().default(false),
  // encryptionPolicy: z.enum(["none", "requireEncryption"]),
  // playStoreMode: z.enum(["allow", "whitelist", "blacklist"]),
  // locationMode: z.enum(["highAccuracy", "batterySaving", "sensorsOnly", "off"]),
  networkEscapeHatchEnabled: z.boolean().default(false),
  bluetoothDisabled: z.boolean().default(false),
  funDisabled: z.boolean().default(false),
  // cameraAccess: z.enum(["allow", "deny", "askUser"]),
  // microphoneAccess: z.enum(["allow", "deny", "askUser"]),
});

export const createPolicyFormSchema = createPolicySchema.extend({
  displayName: z.string().trim().min(1),
});
