import AppsMenuBar from "@/app/(main)/components/projects/app-menu-ber";
import type { Metadata } from "next";
import { PublicAppsProvider } from "../providers/public-apps";
import { AppsInfoSheetProvider } from "../providers/apps-info-sheet";
import AppInfoSheet from "./public/components/app-info-sheet";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PublicAppsProvider>
      <AppsInfoSheetProvider>
        <div className="flex">
          <AppsMenuBar className="hidden xl:block" />
          <div className="flex-1 min-w-0">{children}</div>
        </div>
        <AppInfoSheet />
      </AppsInfoSheetProvider>
    </PublicAppsProvider>
  );
}
