import AppsMenuBar from "@/app/(main)/components/projects/app-menu-ber";
import type { Metadata } from "next";
import { PublicAppsProvider } from "../providers/public-apps";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PublicAppsProvider>
      <div className="flex">
        <AppsMenuBar className="hidden lg:block" />
        <div className="flex-1 min-w-0">{children}</div>
      </div>
    </PublicAppsProvider>
  );
}
