import type { Metadata } from "next";
import Header from "../components/header";
import WaveAnimation from "../components/wave-animation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col relative overflow-hidden">
      <Header />
      <div className="flex-1 -translate-y-16 xl:translate-y-1 2xl:translate-y-16 z-50">
        {children}
      </div>
      <div className="absolute bottom-0 left-0 w-full">
        <WaveAnimation />
      </div>
    </div>
    // <>
    //   <Header />
    //   <main className="flex-1">{children}</main>
    //   <WaveAnimation />
    // </>
  );
}
