import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "../components/theme-provider";
import Footer from "./components/footer";
import Header from "./components/header";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          "h-dvh flex flex-col"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* ヘッダーを固定しない */}
          {/* <Header />
          {children} */}

          {/* ヘッダーを固定 */}
          <Header className="fixed top-0 left-0 w-full z-10 bg-background" />
          <div className="mt-[56px] md:mt-[76px]">{children}</div>

          {/* うまく調整できなかった */}
          {/* <div className="fixed bottom-4 right-10">
            <ModeToggle />
          </div> */}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
