import type { Metadata } from "next";
import NavigationBar from "../../components/projects/navigation-ber";
import { PolicyProvider } from "./providers/policy";
import { EnterpriseProvider } from "./providers/enterprise";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <EnterpriseProvider>
      <PolicyProvider>
        <div className="flex">
          <NavigationBar className="hidden xl:block" />
          {/* <div className="hidden lg:block">
        <NavigationBar />
      </div>
      <div className="lg:hidden">
        <MobileNavigationBar />
      </div> */}
          <div className="flex-1 min-w-0">{children}</div>
        </div>
      </PolicyProvider>
    </EnterpriseProvider>
  );
}
