import PoliciesMenuBar from "@/app/(main)/components/policies-menu-bar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <PoliciesMenuBar />
      <div className="flex-1">{children}</div>
    </div>
  );
}
