import type { Metadata } from "next";
import { PolicySidebar } from "./components/policy-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-dvh">
      <PolicySidebar />
      {/* <PolicySidebarR1 className="hidden xl:block bg-sidebar" /> */}
      <div className="flex-1 min-w-0">{children}</div>
    </div>
  );
}
