import type { Metadata } from "next";

import { ModeToggle } from "@/components/mode-toggle";
import Header from "../(marketing)/components/header";
import Footer from "../(marketing)/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header className="sticky top-0 z-10 bg-background" />
      <main className="flex-1">{children}</main>
      <div className="fixed bottom-4 right-5 z-50">
        <ModeToggle />
      </div>
      <Footer />
    </>
  );
}
