import type { Metadata } from "next";
import { DeviceSidebar } from "./components/device-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      {/* <DeviceSidebar /> */}
      <DeviceSidebar className="hidden xl:block" />
      {/* <DevicesMenuBar className="hidden md:block" /> */}
      {/* <DevicesMenuBar
        className={cn(
          "w-80 hidden lg:block",
        )}
      /> */}
      {/* <MobileDevicesMenuBar /> */}
      <div className="flex-1 min-w-0">{children}</div>
    </div>
  );
}
