import type { Metadata } from "next";
import NavigationBar from "../components/projects/navigation-ber";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import { GapiIframesProvider } from "./providers/gapi-iframes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ enterpriseId: string }>;
}>) {
  const enterpriseId = (await params).enterpriseId;
  const cookieStore = await cookies();
  const sidebarState = cookieStore.get("sidebar:state")?.value;
  const defaultOpen =
    sidebarState === undefined ? true : sidebarState === "true"; // クッキーが存在しない場合（初回アクセス時）はsidebarStateがundefinedなのでtrue
  return (
    <GapiIframesProvider>
      <div className="flex">
        <NavigationBar
          className="hidden xl:block"
          enterpriseId={enterpriseId}
        />
        <SidebarProvider defaultOpen={defaultOpen} className="min-w-0">
          {/* <div className="hidden lg:block">
        <NavigationBar />
      </div>
      <div className="lg:hidden">
        <MobileNavigationBar />
      </div> */}
          <div className="flex-1 min-w-0">{children}</div>
        </SidebarProvider>
      </div>
    </GapiIframesProvider>
  );
}
