import type { Metadata } from "next";
import WaveAnimation from "./components/wave-animation";
import Header from "./components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col relative overflow-hidden">
      <Header />
      <main className="flex-1 z-50">{children}</main>
      <div className="absolute bottom-0 left-0 w-full">
        <WaveAnimation />
      </div>
    </div>
  );
}
