import DevicesMenuBar from "@/app/(main)/components/devices-menu-bar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <DevicesMenuBar />
      <div className="flex-1 min-w-0 overflow-hidden">{children}</div>
    </div>
  );
}
